build: off

image:
  - Ubuntu
  - Visual Studio 2019

init:
  - git config --global core.autocrlf input

for:
-
  matrix:
    only:
      - image: Ubuntu

  branches:
    only:
      - build-graal
  artifacts:
  - path: client/target/graalcp/sbt.client.client
    name: linux-sbt-client

  install:
  - curl -sL https://github.com/sbt/sbt/releases/download/v1.3.10/sbt-1.3.10.tgz > ~/sbt-bin.tgz
  - mkdir ~/sbt
  - tar -xf ~/sbt-bin.tgz --directory ~/sbt
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.0/install.sh | bash && . ~/.jabba/jabba.sh
  - jabba install adopt@1.8.0-222
  - jabba use adopt@1.8.0-222
  - curl -sL https://github.com/graalvm/graalvm-ce-dev-builds/releases/download/20.2.0-dev-20200522_0210/graalvm-ce-java8-linux-amd64-20.2.0-dev.tar.gz > ~/graalvm.tar.gz 
  - tar -xf ~/graalvm.tar.gz --directory ~/.
  - export PATH="$PATH:~/graalvm-ce-java8-20.2.0-dev/bin"
  - gu install native-image
  - export JAVA_HOME="~/.jabba/jdk/adopt@1.8.0-222"
  - export PATH="$PATH:~/.jabba/jdk/adopt@1.8.0-222/bin"
  - export PATH="~/sbt/sbt/bin:$PATH"
  - export SBT_OPTS="-XX:MaxPermSize=1g -Xmx1g -Dfile.encoding=UTF8"

  cache:
    - /home/appveyor/.jabba/jdk
    - /home/appveyor/.sbt

  test_script:
    - sbt "jline2/publishLocal; ipcsocket / publishLocal"
    - sbt "sbtClientProj/genNativeExecutable"


-
  matrix:
    only:
      - image: Visual Studio 2019
  branches:
    except:
      - build-graal
  install:
    - cinst jdk8 -params 'installdir=C:\\jdk8'
    - SET JAVA_HOME=C:\jdk8
    - SET PATH=C:\jdk8\bin;%PATH%
    - SET CI=true

    - ps: |
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        if (!(Test-Path -Path "C:\sbt" )) {
          (new-object System.Net.WebClient).DownloadFile(
            'https://github.com/sbt/sbt/releases/download/v1.3.10/sbt-1.3.10.zip',
            'C:\sbt-bin.zip'
          )
          [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
        }
    - SET PATH=C:\sbt\sbt\bin;%PATH%
    - SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g -Dsbt.supershell=never -Dfile.encoding=UTF8

  cache:
    - '%USERPROFILE%/.sbt'

  test_script:
    - sbt "jline2/publishLocal; ipcsocket / publishLocal"
    - sbt "scripted actions/* classloader-cache/* nio/* watch/*" "testOnly sbt.ServerSpec"

