dist: xenial

language: scala

env:
  global:
    - TRAVIS_JDK=adopt@1.11.0-1
    - SCALA_212=2.12.12
    - SCALA_213=2.13.1
    - UTIL_TESTS="utilCache/test;utilControl/test;utilInterface/test;utilLogging/test;utilPosition/test;utilRelation/test;utilScripted/test;utilTracking/test"
    # WHITESOURCE_PASSWORD=
    - SBT_VERSION_PROP=""
    - SBT_LOCAL=false
    - secure: d3bu2KNwsVHwfhbGgO+gmRfDKBJhfICdCJFGWKf2w3Gv86AJZX9nuTYRxz0KtdvEHO5Xw8WTBZLPb2thSJqhw9OCm4J8TBAVqCP0ruUj4+aqBUFy4bVexQ6WKE6nWHs4JPzPk8c6uC1LG3hMuzlC8RGETXtL/n81Ef1u7NjyXjs=
  matrix:
    - SBT_CMD="publishLocalBin; serverTestProj/test"
    - SBT_CMD="publishLocalBin; mainProj/compile; serverTestProj/test"
    - SBT_CMD="publishLocalBin; commandProj/compile; serverTestProj/test"
    - SBT_CMD="publishLocalBin; buildThinClient; serverTestProj/test"

matrix:
  fast_finish: true
  include:
    - env:
        - SBT_LOCAL=true
        - SBT_VERSION_PROP=-Dsbt.version=1.4.0-SNAPSHOT
        - TRAVIS_JDK=adopt@1.8.0-222
        - SBT_CMD="publishLocalBin; serverTestProj/test"

before_install:
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.0/install.sh | bash && . ~/.jabba/jabba.sh
  - if [ $SBT_LOCAL == true ]; then sbt -Dsbt.io.virtual=false publishLocalBin; fi
  - rm -r $(find $HOME/.sbt -name "*-SNAPSHOT") || true

install:
  - $JABBA_HOME/bin/jabba install $TRAVIS_JDK
  - $JABBA_HOME/bin/jabba install openjdk@1.10
  - unset _JAVA_OPTIONS
  - export JAVA_HOME="$JABBA_HOME/jdk/$TRAVIS_JDK" && export PATH="$JAVA_HOME/bin:$PATH" && java -Xmx32m -version

script:
  # It doesn't need that much memory because compile and run are forked
  - sbt publishLocalBin
  - sbt -Dsbt.version=1.4.0-SNAPSHOT -Dsbt.io.virtual=false $SBT_VERSION_PROP -Dsbt.ci=true -J-XX:ReservedCodeCacheSize=128m -J-Xmx800M -J-Xms800M -J-server "$SBT_CMD"
  - echo "should be done"

before_cache:
  - find $HOME/.cache/coursier/v1 -name "ivydata-*.properties" -delete
  - find $HOME/.ivy2              -name "ivydata-*.properties" -delete
  - find $HOME/.sbt               -name "*.lock"               -delete
  - rm -r $(find $HOME/.sbt -name "*-SNAPSHOT") || true

cache:
  directories:
    - $HOME/.cache/coursier/v1
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.jabba
